### ISSUE TITLE
Bacth generation for LIDC dataset

### ISSUE THREAD

**Issue by maxmanko** [MIC-DKFZ/medicaldetectiontoolkit#15]
Hello Paul,

Thank you for your repo, you did amazing work! I executed your code with LIDC dataset and it works.

I work on my custom modification of 3D RetinaNet in Keras. But it doesn't work.  I'm going to figure out with your pipeline and maybe it will help me to find bugs in my code. 

I visualized batch from LIDC BacthGenerator and I can't figure out one thing. In the segmentation mask, nonzero values are present only in 2 samples (samples 4 and 5). But, at the same time, the class_target is as follows:

Class target: [list([]) list([0]) list([1, 0]) list([1, 0])
 list([0, 1, 1, 1, 0, 1, 1, 0]) list([0]) list([0]) list([1])]

I thought the class_target contains labels of the belonging of nodules to a class. I checked other batches and there is the same situation. I will be very appreciated if you explain why the class_target looks like this.

**Comment by pfjaeger** [comment]
hi, thank you for the feedback.
where in the code do you get these outputs? 
class targets with values [0,1] are present before ConvertSegToBoundingBoxCoordinates, where values are modified via +=1 to make space for the 0=background class. So something is wrong in your data loader. Do you call the ConvertSegToBoundingBoxCoordinates method?

'I thought the class_target contains labels of the belonging of nodules to a class' - this is correct.
So in your output dict from load_dataset, batch elements with seg !=0 need to have filled class target lists, and empty segs need to have empty class target lists. otherwise your preprocessed data is incorrect.

Feel free to follow up on this comment and provide further info to figure this out.
