### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by teemoeric** [MIC-DKFZ/medicaldetectiontoolkit#37]
Hi 
I am doing a projet which used to fully automated quantitative
cephalometry in X-ray images. They are on 2D.
So I want to know which type of annotation file I need for trainning?
I have a csv file with all the coordinates of these bounding boxes in each images? Is that ok for your script?

Thank you so much

**Comment by pfjaeger** [comment]
hi,
yes this is ok. If you look at the figure in the readme section "Training annotations", you can see that box annotations are transformed into pseudo masks to undergo data augmentation and later retransformed to boxes. The only step you need to do is in your data loader method "generate_train_batch" instead of segmentation maps you load the coordinates and print them as ones into a zero array. the rest is done by the framework.
