### ISSUE TITLE
Pytorch 1.0

### ISSUE THREAD

**Issue by IvanBarabanau** [MIC-DKFZ/medicaldetectiontoolkit#41]
Hi! Are you planning to migrate to Pytorch 1.0?

**Comment by pfjaeger** [comment]
yes should be no problem, i will include this in the next commit, thanks for the hint!

**Comment by pfjaeger** [comment]
bad news: the cuda code used in this repo uses ffi which is deprecated since torch==1.0.1 (See https://github.com/pytorch/pytorch/issues/15645). So this repo is currently stuck on torch==0.4.1 and I will not have time in the near future to replace or re-write all cuda code.

Those guys apparently got it working on the developer's branch of version 1.0:
https://github.com/jwyang/faster-rcnn.pytorch/issues/412

Please let me know if anyone has an idea on how to fix this.

**Comment by justusschock** [comment]
For the 2d version you could probably use the cuda-extensions from [torchvision](https://github.com/pytorch/vision/pull/826). Maybe you'd want to wait for a official release there.

**Comment by Gregor1337** [comment]
A version with updated torch dependency is already available in the development branch torch1x and will soon be merged into the master.
