### ISSUE TITLE
Bounding box annotations input issue

### ISSUE THREAD

**Issue by zihaozhihao** [MIC-DKFZ/medicaldetectiontoolkit#64]
In the READEME.md, it's pointed out that the framework could be trained with two kinds of input, one is pixel-wise annotations and other one is bbox annotations. Is there any part from the framework could do to generate pseudo mask for the user? Seems like we need to generate the pseudo mask by ourselves.

**Comment by pfjaeger** [comment]
yes sorry, there is no example dataloader for box annotations, but the solution is straightforward: e.g. in lidc dataloader line 237 you would load box annotations instead of gt segmentations from your data set. Then simply create a zero numpy array and fill it with ones inside the bbox coordinates. Should be one extra line :)
