### ISSUE TITLE
For LIDC, do you use only one scan per patient?

### ISSUE THREAD

**Issue by Riksi** [MIC-DKFZ/medicaldetectiontoolkit#7]
In several places in lidc_exp the patient id `pid` is used as a unique identifier for a scan, for example as a dictionary key. `pid` also used to generate train/val/test splits within `data_loader.get_train_generators`. Since there are fewer patients than scans in the LIDC dataset it looks like either a new id has been created for each scan or that you have kept only one scan per patient. If you have created new ids then the splits would not be on a patient level so the same patient could appear in different splits. Could you clarify this?

**Comment by pfjaeger** [comment]
Very good point. There might actually have been a miscommunication with my colleague who did the data conversion and separate scans of the same patient have been treated as different patients, hence can appear in different data set splits ( though this should only be the case for a very small amount of patients?). I willt check this in depth when I’m back in office (15.1) and provide a fix in the data loader / pre processor .

**Comment by pfjaeger** [comment]
Sorry for the long wait. Fortunatelly, the nrrd files coming from the data conversion tool are named with patient ids + time step in letters. Since the vast majority of patients only has one time step (scan), their folder name looks something like: '0998a', '1001a'.  Additional timesteps are then named '0998b', '0998c', etc.  The easiset solution to the problem would be to simply dissmiss the 25 additional time steps in the data set. This boils down to just adding folders with 'a' in the name to the list of data to be preprocessed. So in preprocessing.py line 115:

`paths = [os.path.join(cf.raw_data_dir, ii) for ii in os.listdir(cf.raw_data_dir) if 'a' in ii]`

If you want to keep the 25 additional time steps in the data set you could e.g. only take them out of the training but keep them in the testing. This could be done by adding to the data_loader line 158

`if 'a' in pid:`

What are your thoughts on this? Of course, if you want to compare and benchmark results, it would be nice to find a common standardized procedure to deal with this.
