### ISSUE TITLE
What's the difference between class_target and roi_labels? 

### ISSUE THREAD

**Issue by catmangoeswild** [MIC-DKFZ/medicaldetectiontoolkit#98]
Hello.  In your toy example, the train data generator yields a dictionary, which contains class_target, roi_labels and other important information. The values in class_target are 0s and 1s, while the values in roi_labels are 1s and 2s (circles_scale dataset of toy example). Does class_target refer to bounding box labels and roi_labels refer to mask roi labels? Are they (class_target and roi_labels) essentially the same to each other? 

I have an object detection dataset that contains bounding box coordinates and labels (no masks). If you don't mind, can I ask in this dataset, what's class_target and what's roi_labels? 

Thank you -Bohan Yang

**Comment by Gregor1337** [comment]
Hi Bohan Yang,
you are correct, batch entries "class_target" and "roi_labels" are exactly the same, except that "roi_labels" are shifted by +1 versus "class_target". I.e., both represent the class labels of RoIs.
Mask information, however, is contained in the entries "seg" and "roi_masks" (where the latter is only relevant for model Mask R-CNN).

class_targets are meant to be the class labels during preprocessing, where there is no use for background RoIs. During batch generation they are shifted in the batchgenerators functions ConvertSegToBoundingBoxCoordinates by +1 since model heads indeed need to classify RoIs as background, which is taken to be the class with label 0. 


I hope this clarifies your question regarding your mentioned dataset.
